### ISSUE TITLE
kv-v2 with vault_mount forces re-creating existing resource

### ISSUE THREAD

**Issue by rsjorslev** [terraform-providers/terraform-provider-vault#442]
### Terraform Version
Terraform v0.11.11
+ provider.vault v1.8.0

### Vault Version
1.1.2

### Affected Resource(s)
- vault_mount

### Terraform Configuration Files
```hcl
resource "vault_mount" "test_kvv2" {
  path        = "test_kvv2"
  type        = "kv-v2"
  description = "kv-v2 testing"
}
```

### Expected Behavior
Upon re-running terraform apply I would have expected the `vault_mount` resource to not be destroyed and then re-created.

### Actual Behavior
terraform seems to force a re-creation of the resource resulting in all secrets currently stored in the engine to be deleted.
I have tried this with the vault module v. 1.3.0, 1.3.1 and 1.8.0 and im seeing the same behaviour.
```
-/+ vault_mount.test_kvv2 (new resource required)
      id:                        "test_kvv2" => <computed> (forces new resource)
      accessor:                  "kv_26b14ba4" => <computed>
      default_lease_ttl_seconds: "0" => <computed>
      description:               "kv-v2 testing" => "kv-v2 testing"
      max_lease_ttl_seconds:     "0" => <computed>
      options.%:                 "1" => "0"
      options.version:           "2" => ""
      path:                      "test_kvv2" => "test_kvv2"
      type:                      "kv" => "kv-v2" (forces new resource)
```

listing the out from `vault secrets list` seems to suggest it's actually v2:
```
Path          Plugin       Accessor              Default TTL    Max TTL    Force No Cache    Replication    Seal Wrap    Options           Description
----          ------       --------              -----------    -------    --------------    -----------    ---------    -------           -----------
test_kvv2/    kv           kv_61b95585           system         system     false             replicated     false        map[version:2]    kv-v2 testing
```

### Steps to Reproduce
1. `terraform apply`

### References
Not sure if its a regression but issue #140 seems to be related.
- GH-140

**Comment by rnurgaliyev-s11** [comment]
This can be easily temporarily solved by rewriting resource this way:
```
resource "vault_mount" "test_kvv2" {
  path = "test_kvv2"
  type = "kv"
  description = "kv-v2 testing"

  options {
    version = 2
  }
}
```

**Comment by rsjorslev** [comment]
I still get this even when specifying that in options:

```
-/+ vault_mount.test_kvv2 (new resource required)
      id:                        "test_kvv2" => <computed> (forces new resource)
      accessor:                  "kv_c1026c03" => <computed>
      default_lease_ttl_seconds: "0" => <computed>
      description:               "kv-v2 testing" => "kv-v2 testing"
      max_lease_ttl_seconds:     "0" => <computed>
      options.%:                 "1" => "1"
      options.version:           "2" => "2"
      path:                      "test_kvv2" => "test_kvv2"
      type:                      "kv" => "kv-v2" (forces new resource)
```

I initially created it with that options block defined as well.
